services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: invoice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d invoice"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  invoice-app:
    build:
      context: .
      target: production
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/invoice
      DATABASE_USE_NEON_WEBSOCKETS: "false"
    command: ["node", "dist/index.js"]
    tty: true
