services:
  invoice-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTOMATION_SECRET: ${AUTOMATION_SECRET}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET:-}
      WEBHOOK_ALLOWED_DOMAINS: ${WEBHOOK_ALLOWED_DOMAINS:-localhost,127.0.0.1}
      DEFAULT_SELLER_NAME: ${DEFAULT_SELLER_NAME:-}
      DEFAULT_SELLER_NIP: ${DEFAULT_SELLER_NIP:-}
      DEFAULT_SELLER_ADDRESS_1: ${DEFAULT_SELLER_ADDRESS_1:-}
      DEFAULT_SELLER_ADDRESS_2: ${DEFAULT_SELLER_ADDRESS_2:-}
      DEFAULT_SELLER_PHONE: ${DEFAULT_SELLER_PHONE:-}
      DEFAULT_SELLER_BANK: ${DEFAULT_SELLER_BANK:-}
      DEFAULT_SELLER_BANK_ADDRESS: ${DEFAULT_SELLER_BANK_ADDRESS:-}
      DEFAULT_SELLER_IBAN: ${DEFAULT_SELLER_IBAN:-}
    ports:
      - "5001:5000"
    networks:
      - docker-project_default

networks:
  docker-project_default:
    external: true
